name: BSD

on: [push, pull_request]

env:
  SPEC_SPLIT_DOTS: 160

jobs:
  test_freebsd:
    runs-on: macos-latest
    env:
      TRAVIS_OS_NAME: freebsd
    steps:
    - uses: actions/checkout@v2
    - name: Test in FreeBSD
      id: test
      uses: vmactions/freebsd-vm@v0.1.2
      with:
        envs: "TRAVIS_OS_NAME SPEC_SPLIT_DOTS"
        usesh: true
        mem: 8192
        prepare: pkg install -y crystal shards gmake llvm10 pkgconf libyaml libxml2 openssl gmp
        run: |
          LLVM_CONFIG=llvm-config10 gmake std_spec clean threads=1 junit_output=.junit/std_spec.xml
